### ISSUE TITLE
Recipe fails compile phase on Ubuntu 14.04 (trusty)

### ISSUE THREAD

**Issue by ronabop** [christianewillman/sonarqube#16]
```
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/sonarqube/resources/plugin.rb
================================================================================

NoMethodError
-------------
undefined method `property' for #<Class:0x0000000696b350>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/sonarqube/resources/plugin.rb:1:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/sonarqube/resources/plugin.rb:

  1>> property :plugin_name, String, name_property: true
  2:  property :version, String
  3:
  4:  actions :install, :uninstall
  5:  default_action :install
  6:
  7:  sonarqube_user = node['sonarqube']['user']
  8:  sonarqube_group = node['sonarqube']['group']
  9:
 10:  action :install do

```

**Comment by christianewillman** [comment]
Hi there, what version of Chef and Ruby are you using?

**Comment by ronabop** [comment]
chmarar@sqube02:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
chmarar@sqube02:~$ chef-client --version
Chef: 12.4.3

**Comment by ronabop** [comment]
root@sqube02:/home/STAGINGDMZ/chmarar# chef-client --version
Chef: 12.8.1
Works, so somewhere between those two there's a break point.

**Comment by christianewillman** [comment]
The LWRP syntax I'm using in `resources/plugin.rb` was introduced in Chef 12.5 (see https://docs.chef.io/custom_resources.html).

If you absolutely need support in Chef 12.4.x, then I would graciously accept a PR, and I might have some time to re-write the LWRP in a backwards-compatible way some time soon.
