### ISSUE TITLE
Sonhrqube restarts with each Chef converge

### ISSUE THREAD

**Issue by zanshin** [christianewillman/sonarqube#17]
I'm using the sonarqube::default recipe to install Sonar along side our Jenkins installation. Every 15 minutes when the node converges, Sonar is restarted. I think the problem is here:

```
service 'sonarqube' do
  supports restart: true, reload: false, status: true
  action [:enable, :start]
end
```

Doesn't having :start in the action line cause it to start each time the node converged? Or am I missing something?

**Comment by dschlenk** [comment]
@zanshin what OS? I'm not seeing this problem in CentOS 6.8.

**Comment by zanshin** [comment]
The problem was related to Chef. The `:start` action causes the server to start when the recipe runs. And since Chef is configured to run every 15 minutes ...

PEBKAC.
