### ISSUE TITLE
Need a general configuration resource

### ISSUE THREAD

**Issue by kbaltrinic** [christianewillman/sonarqube#4]
@pghalliday, you were so gracious and expedient with fix for Issue 3 that am encourage to ask for one more feature.  The `jdbc` resource is nice and all but it pretty limitted.  It would be great if there was a general purpose resource for setting any value in the config file, or ideally a block of config values all at once (for example the `sonar.security` and `ldap` values for the [LDAP plugin](http://docs.sonarqube.org/display/SONAR/LDAP+Plugin))  

A simpler though less handy solution would simply be to expose the location of the install as node property so that we can get at the `/conf` directory ourselves without needing any magic knowledge of the internals of the sonarqube cookbook.  

Now I am asking for the moon, but to completely round out this cookbook, a resource to set properties stored on the properties table in the database, and the ability to set [encrypted property values](http://docs.sonarqube.org/display/SONAR/Settings+Encryption) would be killer features. ;-)

**Comment by pghalliday** [comment]
I have a tendency to only implement features I use, however I do accept merge requests ;) (also on vacation right now so won't likely look at this for a few days)

**Comment by kbaltrinic** [comment]
If I can find the time, I might possibly try my hand at this, but I warn you, when it comes to Ruby, I'm a complete hack.

**Comment by christianewillman** [comment]
@kbaltrinic You may define a list of arbitrary properties in `node['sonarqube']['extra_properties']`, where each key-value pair is a string.

```json
"sonarqube": {
  "extra_properties": [
    "sonar.security.realm=LDAP",
    "sonar.security.savePassword=false"
  ]
}
```
